title: Jan Knappe
description: a personal blog on science, coding, and globetrotting

url: http://janknappe.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: Coding
   url: /pages/coding
 - title: Science
   url: /pages/science
 - title: Photography
   url: /pages/photography
 - title: CV
   url: /pages/cv
 - title: About
   url: /pages/about
 - title: Contact
   url: /pages/contact

social:
   github: jknappe
   twitter: janknappe
   email: jan.knappe@gmail.com

google_analytics: "UA-111480581-1"
