# SITE SETTINGS
#====================================
name: Jan Knappe
description: Environmental Scientist
avatar: https://www.janknappe.com/images/jan-knappe.jpg

# NAVIGATION
#====================================
navigation:
  - name: Blog
    url: /	
  - name: Projects
    url: /projects
  - name: About
    url: /about
#  - name: Archive
#    url: /archive
#  - name: Tags
#    url: /tags

# Pagination
paginate: 20

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: jan.knappe@gmail.com
  facebook:
  flickr: 
  github: jknappe
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin: janknappe/
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: users/9338997/jknappe
  tumblr: # https://<username>.tumblr.com
  twitter: JanKnappe
  youtube: # channel/<your_long_string> or user/<user-name>

# Text under the icons in footer
footer-text: This websited is hosted powered by [GitHub Pages](https://pages.github.com/) and [Jekyll](https://jekyllrb.com/) and maintained by [Jan Knappe](https://www.janknappe.com/).


disqus: janknappe.disqus.com
google_analytics: UA-111480581-1

url: https://www.janknappe.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
